{lib}: {
  globalProperties ? {},
  components ? [],
}: (builtins.concatStringsSep "\n" [
  ''
    # This file is automatically generated by grub-theme.nix
    # DO NOT EDIT
  ''

  (builtins.concatStringsSep "\n"
    (lib.mapAttrsToList (name: value: ''${name}: "${builtins.toString value}"'')
      globalProperties))

  (builtins.concatStringsSep ""
    (builtins.map (component:
      builtins.concatStringsSep "\n" (lib.mapAttrsToList (type: properties: ''

          + ${type} {
            ${builtins.concatStringsSep "\n  "
            (lib.mapAttrsToList (key: value: ''${key} = "${builtins.toString value}"'') properties)}
          }
        '')
        component))
    components))
])
